name: release

on:
  push:
    branches: [master]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sage
        uses: einride/sage/actions/setup@master
        with:
          go-version: "1.20"

      - name: Make
        run: make

      - name: Run semantic-release
        run: make semantic-release repo=${{ github.repository }} dry=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        run: make go-releaser snapshot=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
